digipay/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path("",include('accounts.urls')),
    path("kyc/",include('bankaccounts.urls')),
    path("search_user/",include("transactions.urls")),
    path('admin/', admin.site.urls,name="admin"),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

transactions/urls.py
from django.urls import path
from transactions import transfer,payment_request,credit_card
from bankaccounts.models import Account
app_name="transactions"
urlpatterns=[
    path("",transfer.search_user_by_acc_num,name="search"),
    path("amount_transfer/<account_number>/",transfer.amount_transfer,name="amount_transfer"),
    path("amount_transfer_process/<account_number>/",transfer.amount_transfer_process,name="amount_transfer_process"),
    path("transfer_confirmation/<account_number>/<transaction_id>/",transfer.transfer_confirmation,name="transfer-confirmation"),
    path("transfer_success/<account_number>/<transaction_id>/",transfer.transfer_success,name="transfer-success"),
    path("transaction_detail/<transaction_id>/",transfer.transaction_detail,name="transaction_detail"),
    path("user_request_payment/",payment_request.user_request_payment_by_accnum,name="user_request_payment"),
    path("request_amount/<account_number>/",payment_request.request_amount,name="request_amount"),
    path("request_confirmation/<account_number>/<transaction_id>/",payment_request.request_confirmation,name="request_confirmation"),
    path("request_success/<account_number>/<transaction_id>/",payment_request.request_success,name="request_success"),
    path("transaction_list/",transfer.transaction_list,name="transaction_list"),
    path("send_confirmation/<account_number>/<transaction_id>/",payment_request.send_Confirmation,name="send_confirmation"),
    path("send_completed/<account_number>/<transaction_id>/",payment_request.send_processing,name="send_completed"),
    path("send_amount_completed/<account_number>/<transaction_id>/",payment_request.send_amount_completed,name="send_amount_completed"),
    path("creditcard/<number>/<account_number>/",credit_card.credit_card_detail,name="credit_card_detail"),
    path("credit_card_bill/<card_id>/",credit_card.credit_card_bill,name="credit_card_bill"),
    path("withdraw_amount/<card_id>/",credit_card.withdraw_amount,name="withdraw_amount_card"),
    path("delete_Card/<card_id>/",credit_card.delete_card,name="delete_card")
]

templates/core/amount_transfer.html
{% extends "partials/dashbord_base.html" %}
{% load static %}
{% load humanize %}
{% block content %}
    <!-- Dashboard Section start -->
    <section class="dashboard-section body-collapse pay step step-2">
        <div class="overlay pt-120">
            <div class="container-fruid">
                <div class="main-content">
                    <div class="head-area d-flex align-items-center justify-content-between">
                        <h4>Make a Payment</h4>
                        <div class="icon-area">
                            <img src="{% static 'assets1/images/icon/support-icon.png' %}" alt="icon">
                        </div>
                    </div>
                    <div class="choose-recipient">
                        <div class="step-area">
                            <span class="mdr">Step 2 of 3</span>
                            <h5>Set Amount of transfer</h5>
                        </div>
                        <div class="user-select">
                            <div class="single-user">
                                <div class="left d-flex align-items-center">
                                    <div class="img-area">
                                        <!-- <img src="{{ a.user.kyc.image.url }}" alt="image"> -->
                                        <img src="{{ account.user.kyc.image.url }}" style="width: 100px; height: 100px; border-radius: 50%; object-fit: cover;"  alt="image">
    
                                    </div>
                                    <div class="text-area">
                                        <p>{{ account.user.kyc.full_name|title }}</p>
                                        <span class="mdr"><b>{{ account.account_number }}</b></span> <br>
                                        <span class="mdr">{{ account.user.kyc.email }}</span>
                                    </div>
                                </div>
                                <div class="right">
                                    
                                    <a href="{%url 'transactions:search'%}">
                                        <i class=""></i>
                                        Edit
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <form action="#" method="POST">
                        {% csrf_token %}
                        <div class="send-banance">
                            <span class="mdr">You Send</span>
                            <div class="input-area">
                                <input class="xxlr" onkeyup="CalculateBalance()" placeholder="Rs.{{account.account_balance|intcomma}}" type="number" name="amount-send" id="amount-send">
                            </div>
                            <p>Available Balance<b>Rs.{{account.account_balance|intcomma}}</b></p>
                            <p id="new_balance"></p>
                            <p class="text-danger" id="error-div"></p>
                        </div>
                        <!-- Js -->

                        <div class="send-banance pt-0 mt-0">
                            <span class="mdr">Payment Description</span>
                            <div class="input-area">
                                <input class="xxlr" onkeyup="CalculateBalance()" placeholder="Payment for fees" type="text" name="description">
                                
                            </div>
                        </div>
                        <script>
                            function CalculateBalance(){
                                let available_balance = "{{ request.user.account.account_balance }}" // Get users current account balance 
                                let new_balance = document.getElementById("new_balance")
                                let sendAmount_input = document.getElementById("amount-send")
                                let sendAmount = sendAmount_input.value
                                let errorDiv = document.getElementById("error-div")
                                let total_to_pay = document.getElementById("total-to-pay")
                                let errors = []
                                new_bal = available_balance - sendAmount
                                console.log(new_bal);

                                // new_balance.innerHTML = `New Balance $${new_bal.toString().replace(/\B(?))}`
                                new_balance.innerHTML = `New Balance Rs. ${new_bal.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",")} </b>`;
                                total_to_pay.innerHTML = `Rs ${sendAmount.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",")} </b>`;

                                 if (new_bal < 0){
                                    new_balance.style.color = "red"
                                    alert("You can only send Rs." + available_balance.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ","))
                                } else {
                                    new_balance.style.color = "#27276e"

                                }
                            
                            }
                        </script>
                        
                        <ul class="total-fees">
                            <li>Total Fees</li>
                            <li>Free</li>
                        </ul>
                        <ul class="total-fees pay">
                            <li><h5>Total To Pay</h5></li>
                            <li><h5 id="total-to-pay">Rs 0.00</h5></li>
                        </ul>
                        <div class="footer-area mt-40">
                            <a href="pay-step-1.html">Previous Step</a>
                            <button type="submit" style="padding: 10px 30px; border-radius: 10px; background: rgb(98, 0, 255); color: #fff;" class="active">Next</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <!-- Dashboard Section end -->

    {% endblock content %}

templates/core/amount_transfer_process.html
{% extends "partials/dashbord_base.html" %}
{% load static %}
{% load humanize %}
{% block content %}
    <!-- Dashboard Section start -->
    <section class="dashboard-section body-collapse pay step step-2">
        <div class="overlay pt-120">
            <div class="container-fruid">
                <div class="main-content">
                    <div class="head-area d-flex align-items-center justify-content-between">
                        <h4>Make a Payment</h4>
                        <div class="icon-area">
                            <img src="{% static 'assets1/images/icon/support-icon.png' %}" alt="icon">
                        </div>
                    </div>
                    <div class="choose-recipient">
                        <div class="step-area">
                            <span class="mdr">Step 2 of 3</span>
                            <h5>Set Amount of transfer</h5>
                        </div>
                        <div class="user-select">
                            <div class="single-user">
                                <div class="left d-flex align-items-center">
                                    <div class="img-area">
                                        <!-- <img src="{{ a.user.kyc.image.url }}" alt="image"> -->
                                        <img src="{{ account.user.kyc.image.url }}" style="width: 100px; height: 100px; border-radius: 50%; object-fit: cover;"  alt="image">
    
                                    </div>
                                    <div class="text-area">
                                        <p>{{ account.user.kyc.full_name|title }}</p>
                                        <span class="mdr"><b>{{ account.account_number }}</b></span> <br>
                                        <span class="mdr">{{ account.user.kyc.email }}</span>
                                    </div>
                                </div>
                                <div class="right">
                                    <a href="{%url 'transactions:search'%}">
                                        <i class=""></i>
                                        Edit
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <form action="#" method="POST">
                        {% csrf_token %}
                        <div class="send-banance">
                            <span class="mdr">You Send</span>
                            <div class="input-area">
                                <input class="xxlr" onkeyup="CalculateBalance()" placeholder="Rs.{{account.account_balance|intcomma}}" type="number" name="amount-send" id="amount-send">
                            </div>
                            <p>Available Balance<b>Rs.{{account.account_balance|intcomma}}</b></p>
                            <p id="new_balance"></p>
                            <p class="text-danger" id="error-div"></p>
                        </div>
                        <!-- Js -->
                        <div class="send-banance pt-0 mt-0">
                            <span class="mdr">Payment Description</span>
                            <div class="input-area">
                                <input class="xxlr" onkeyup="CalculateBalance()" placeholder="Payment for fees" type="text" name="description">
                                
                            </div>
                        </div>
                        <script>
                            function CalculateBalance(){
                                let available_balance = "{{account.account_balance }}" // Get users current account balance 
                                let new_balance = document.getElementById("new_balance")
                                let sendAmount_input = document.getElementById("amount-send")
                                let sendAmount = sendAmount_input.value
                                let errorDiv = document.getElementById("error-div")
                                let total_to_pay = document.getElementById("total-to-pay")
                                let errors = []
                                new_bal = available_balance - sendAmount
                                console.log(new_bal);

                                // new_balance.innerHTML = `New Balance $${new_bal.toString().replace(/\B(?))}`
                                new_balance.innerHTML = `New Balance Rs. ${new_bal.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",")} </b>`;
                                total_to_pay.innerHTML = `Rs ${sendAmount.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",")} </b>`;

                                 if (new_bal < 0){
                                    new_balance.style.color = "red"
                                    alert("You can only send Rs." + available_balance.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ","))
                                } else {
                                    new_balance.style.color = "#27276e"

                                }
                            
                            }
                        </script>
                        
                        <ul class="total-fees">
                            <li>Total Fees</li>
                            <li>Free</li>
                        </ul>
                        <ul class="total-fees pay">
                            <li><h5>Total To Pay</h5></li>
                            <li><h5 id="total-to-pay">Rs 0.00</h5></li>
                        </ul>
                        <div class="footer-area mt-40">
                            <a href="pay-step-1.html">Previous Step</a>
                            <button type="submit" style="padding: 10px 30px; border-radius: 10px; background: rgb(98, 0, 255); color: #fff;" class="active">Next</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <!-- Dashboard Section end -->

    {% endblock content %}

templates/core/transaction_detail.html
{% extends 'partials/dashbord_base.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        .transaction_detail{
            margin-left: 300px;
            margin-top: 100px;
        }
        .two img{
            height: 120px;
            width: 100px;
            margin-left: 50px;
            margin-top: -10px;
            
            
        }
        .ot{
            display: flex;
            
        }
        h4{
            text-decoration: underline;
        }
        .rec{
            margin-top: 20px;
        }
    </style>
</head>
<body>
    <div class="transaction_detail">
        <div class="ot">
        <div class="one">
        <p>{{account.user}}</p>
        <p>{{account.account_number}}</p>
        <p>{{account.account_id}}</p>
    </div>
    <div class="two">
        <img src={{kyc.image.url}} alt="">
    </div>
</div>

        <h4 class="rec">Receiver Details</h4>
        <p>{{receiver}}</p>
        <p>{{transaction.amount}}</p>
        <p>{{receiver.account.account_number}}</p>
        <p>{{receiver.account.account_id}}</p> <br>
        <h4>Kyc Details</h4>
        <p>{{kyc.gender}}</p>
        <p>{{kyc_id}}</p>
        <p>{{kyc.date_of_birth}}</p> <br>
        <h4>Transaction-Details</h4>
        <p>{{transaction.transaction_id}}</p>
        <p>{{transaction.description}}</p>
        <p>{{transaction_amount}}</p>
        <p>{{transaction.date}}</p>
        <p>{{transaction.status}}</p>
        <p>{{transaction.transaction_type}}</p>
    </div>
    
</body>
</html>
{% endblock content %}

templates/core/transactions_list.html
{% extends 'partials/dashbord_base.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <style>
    .main{
      margin-left: 400px;
      margin-top: 100px;
    }
    h4{
      text-decoration: underline;
    }
    .inp{
      display: flex;
      justify-content: space-between;
      text-decoration: underline;
      
    }
    table{
      margin-top: 20px;
     
      
    }
    .transfer{
      color: green;
      border-color: green;
    }
    .received{
      color: blue;
      border-color: blue;
    }
    .in1{
      color: green;
    }
    .in2{
      color: darkgoldenrod;
    }
  </style>
</head>
<body>
    <form action="" method="POST">
        {%csrf_token%}
  <div class="main">
  <div class="container">
    <div class="jumbotron">
        <div class="row">
            <div class="col-md-3">
                <div class="card card-body">
                  <p>Hi!! {{account.user}}</p>
                  <p><b>Rs {{account.account_balance}}</b></p>
                  <p>{{account.account_number}}</p>
                  <div class="inp">
                 <input class="in1" type="submit" value="completed" name="completed">
                 <input class="in2" type="submit" value="request_sent" name="request_sent">
                </div>
                </div>
            </div>
        </div>
    </div>
  </div>
  <br>
  
  <h4><b>Recent Transactions</b></h4>
  <table  border="1" cellspacing="3" cellpadding="5"  style="text-align: center;" >
    <tr>
      <th>NAME</th>
      <th>AMOUNT</th>
      <th>DATE</th>
      <th>TRANSACTION_STATUS</th>
      <th>ACTION</th>
    </tr>
    {% if query1 %}
    {%for data in transaction%}
    <tr>
      <td>{{data.receiver}}</td>
      <td>{{data.user}}</td>
      <td>{{data.amount}}</td>
      <td>{{data.date}}</td>
      <td>{{data.status}}</td>
      <td><a href="{%url 'transactions:send_confirmation' data.receiver.account.account_number data.transaction_id%}">Send</a></td>
    </tr>
    {%endfor%}
    {%endif%}
    {%if query2%}
    {%for data in transaction%}
    <tr>
    <td>{{data.user}}</td>
    <td>{{data.amount}}</td>
    <td>{{data.date}}</td>
    <td>{{data.status}}</td>
      <td><a href="{%url 'transactions:transaction_detail' data.transaction_id %}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-bell-fill" viewBox="0 0 16 16">
        <path d="M8 16a2 2 0 0 0 2-2H6a2 2 0 0 0 2 2zm.995-14.901a1 1 0 1 0-1.99 0A5.002 5.002 0 0 0 3 6c0 1.098-.5 6-2 7h14c-1.5-1-2-5.902-2-7 0-2.42-1.72-4.44-4.005-4.901z"/>
      </svg></a></td> 
    </tr>
   {%endfor%}
   {%endif%}
  </table>
</div>
</form>
</body>
</html>
{% endblock content %}

templates/core/transfer_confirmation.html

{% extends "partials/dashbord_base.html" %}
{% load static %}
{% load humanize %}
{% block content %}
    <!-- Dashboard Section start -->
    <section class="dashboard-section body-collapse pay step step-2 step-3">
        <div class="overlay pt-120">
            <div class="container-fruid">
                <div class="main-content">
                    <div class="head-area d-flex align-items-center justify-content-between">
                        <h4>Make a Payment</h4>
                        <div class="icon-area">
                            <img src="{% static 'assets1/images/icon/support.png' %}" alt="icon">
                        </div>
                    </div>
                    <div class="choose-recipient">
                        <div class="step-area">
                            <span class="mdr">Step 3 of 3</span>
                            <h5>Confirm Your Transfer</h5>
                        </div>
                        <div class="user-select">
                            <div class="single-user">
                                <div class="left d-flex align-items-center">
                                    <div class="img-area">
                                        <!-- <img src="{{ a.user.kyc.image.url }}" alt="image"> -->
                                        <img src="{{ account.user.kyc.image.url }}" style="width: 100px; height: 100px; border-radius: 50%; object-fit: cover;"  alt="image">
    
                                    </div>
                                    <div class="text-area">
                                        <p>{{ account.user.kyc.full_name|title }}</p>
                                        <span class="mdr"><b>{{ account.account_number }}</b></span> <br>
                                        <span class="mdr">{{ account.user.kyc.email }}</span>
                                    </div>
                                </div>
                                <div class="right">
                                    
                                    <a href="#">
                                        <i class="icon-h-edit"></i>
                                        Edit
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="payment-details">
                        <div class="top-area">
                            <h6>Payment Details</h6>
                            <div class="right">
                                <a href="javascript:void(0)">
                                    <i class="icon-h-edit"></i>
                                    Edit
                                </a>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xl-6">
                                <ul class="details-list">
                                    <li>
                                        <span>You Send</span>
                                        <b>{{transaction.amount}}</b>
                                    </li>
                                    <li>
                                        <span>Recipient gets</span>
                                        <b>{{transaction.amount}}</b>
                                    </li>
                                    <li>
                                        <span>E-mail </span>
                                        <b>{{ account.user.kyc.email }}</b>
                                    </li>
                                    <li>
                                        <span>Fee</span>
                                        <b>Free</b>
                                    </li>
                                    <li>
                                        <span>Description</span>
                                        <b>{{transaction.description}}</b>
                                    </li>
                                    <li>
                                        <span>Transfer was initiated on </span>
                                        <b>{{transaction.date}} </b>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <form action="#">
                        <div class="checkbox">
                            <input type="checkbox" id="confirm">
                            <label for="confirm">I confirm the payment details above</label>
                        </div>
                        <div class="footer-area mt-40">
                            <a href="pay-step-2.html">Previous Step</a>
                            <a href="javascript:void(0)" class="transferMod active" data-bs-toggle="modal" data-bs-target="#transferMod">Pay</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <!-- Dashboard Section end -->
    
    <!-- Transfer Popup start -->
    <div class="transfer-popup">
        <div class="container-fruid">
            <div class="row">
                <div class="col-lg-6">
                    <div class="modal fade" id="transferMod" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered">
                            <ul class="nav nav-tabs d-none" role="tablist">
                                <li class="nav-item" role="presentation">
                                    <button class="nav-link active" id="transfer-tab" data-bs-toggle="tab"
                                        data-bs-target="#transfer" type="button" role="tab" aria-controls="transfer"
                                        aria-selected="true">transfer</button>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <button class="nav-link" id="success-tab" data-bs-toggle="tab"
                                        data-bs-target="#success" type="button" role="tab" aria-controls="success"
                                        aria-selected="false">Confirm</button>
                                </li>
                            </ul>
                            <div class="tab-content">
                                <div class="tab-pane fade show active" id="transfer" role="tabpanel" aria-labelledby="transfer-tab">
                                    <div class="modal-content">
                                        <div class="modal-header mb-60 justify-content-between">
                                            <a href="javascript:void(0)">
                                                <i class="icon-a-left-arrow"></i>
                                                Back
                                            </a>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"><i class="fa-solid fa-xmark"></i></button>
                                        </div>
                                        <div class="main-content">
                                            <h4>Confirm Transfer!</h4>
                                            <p>Enter your pin number below.</p>
                                            <form  method="POST">
                                                {% csrf_token %}
                                                <div class="userInput">
                                                    <input minlength="4" maxlength="4" name="pin-number" type="text">
                                                </div>
                                                <a href="javascript:void(0)">Reset Pin Number?</a>
                                                <button type="submit" class="mt-60 confirm">Confirm</button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="success" role="tabpanel" aria-labelledby="success-tab">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="btn-close d-md-none d-block" data-bs-dismiss="modal" aria-label="Close"><i class="fa-solid fa-xmark"></i></button>
                                        </div>
                                        <div class="main-content text-center pt-120 pb-120">
                                            <h3>Success</h3>
                                            <p>Transfer was completed.</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Transfer Popup start -->
{% endblock content %}
</html>

templates/core/transfer_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <style>
        #svg{
            margin-left: 700px;
            border-radius: 50px;
        }
        h1{
            margin-top: 30px;
        }
    </style>
</head>
<body>
   
    <h1 align="center"><b>Payment Success</b></h1> <br>
    <svg align="center" xmlns="http://www.w3.org/2000/svg" width="86" height="86" fill="currentColor"  viewBox="0 0 16 16" id="svg" class="btn btn-success">
        <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
      </svg> <br> <br>
      <h3 align="center">Payment of {{transaction.amount}} send to {{transaction.receiver.account.kyc.full_name}}Chowdary</h3>
    
</body>
</html>